# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.box_check_update = true

    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.synced_folder "..", "/comsoljupyter"

    config.vm.provider "virtualbox" do |vb|
        vb.linked_clone = true if Vagrant::VERSION =~ /^1.8/
        vb.memory = 512
        vb.cpus = 2
        # https://github.com/mitchellh/vagrant/issues/7389
        # https://bugs.launchpad.net/cloud-images/+bug/1567259
        vb.customize ["modifyvm", :id, "--name", 'comsoljupyter']
    end

    config.vm.provision "shell", inline: <<-SHELL
        set -e -u
        grep -q nameserver /etc/resolvconf/resolv.conf.d/head || echo 'nameserver 8.8.8.8\nnameserver 8.8.4.4' >> /etc/resolvconf/resolv.conf.d/head
        resolvconf -u
        iptables -A PREROUTING -t nat -p tcp --dport 80 -j REDIRECT --to-port 8080
    SHELL
end
