# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.box_check_update = true

    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.synced_folder "..", "/comsoljupyter"

    config.vm.provider "virtualbox" do |vb|
        vb.linked_clone = true if Vagrant::VERSION =~ /^1.8/
        vb.memory = 512
        vb.cpus = 2
        # https://github.com/mitchellh/vagrant/issues/7389
        # https://bugs.launchpad.net/cloud-images/+bug/1567259
        vb.customize ["modifyvm", :id, "--name", 'comsoljupyter']
    end

    config.vm.provision "shell", inline: <<-SHELL
        set -e -u
        grep -q nameserver /etc/resolvconf/resolv.conf.d/head || echo 'nameserver 8.8.8.8\nnameserver 8.8.4.4' >> /etc/resolvconf/resolv.conf.d/head
        resolvconf -u
        apt-get update
        apt-get install -y python3-pip python3-virtualenv nginx-full ssl-cert libssl-dev virtualenv libyaml-dev libffi-dev
        update-rc.d nginx disable
        service nginx stop

        sudo -u ubuntu -i /bin/bash -l << 'EOF'
            set -e

            test -d $HOME/venv || virtualenv -p python3 $HOME/venv
            source $HOME/venv/bin/activate
            pip install --upgrade pip
            pip install --upgrade setuptools

            cd /comsoljupyter
            pip install -r requirements.txt
            pip install .

            grep -q '$HOME/venv/bin/activate' $HOME/.bashrc || echo 'source $HOME/venv/bin/activate' >> $HOME/.bashrc
EOF

    SHELL
end
